import type { Lang } from "@/lib/i18n";

/** Marketing copy for every page, English and Khmer. Kept deliberately short. */
const en = {
  nav: {
    attendance: "Attendance",
    payroll: "Payroll",
    branches: "Multi-Branch",
    pricing: "Pricing",
    customers: "Customers",
    faq: "FAQ",
    contact: "Contact",
    signIn: "Sign In",
    trial: "Get Started",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "Language",
    currency: "Currency",
    skip: "Skip to content",
  },

  common: {
    trial: "Get Started",
    demo: "Book a demo",
    trialNote: "No setup fee. Pay only for active staff.",
    learnMore: "Learn more",
    seeAll: "See all features",
    talkToSales: "Talk to sales",
  },

  home: {
    badge: "Built for Cambodia",
    title: "Attendance and payroll, done in one place.",
    sub: "GPS-verified clock-in. Automatic overtime and late rules. Payslips in USD and KHR.",
    heroImage: "App clock-in screen and admin dashboard",
    trust: "Built for Cambodian businesses • Phnom Penh, Siem Reap, Sihanoukville",
    pillarsTitle: "Three problems, solved.",
    pillars: [
      {
        title: "Verified clock-in",
        desc: "Staff clock in inside the branch radius, with a selfie. No buddy punching.",
        href: "/attendance",
        image: "Employee clocking in at a branch",
      },
      {
        title: "Automatic payroll",
        desc: "Apply configured overtime, late, and leave rules, then export payslips.",
        href: "/payroll",
        image: "Payroll run summary",
      },
      {
        title: "Every branch",
        desc: "One console for all locations. Managers see their site, owners see everything.",
        href: "/multi-branch",
        image: "Branch overview map",
      },
    ],
    rolesTitle: "Built for the whole team.",
    roles: [
      { role: "Employee", desc: "Clock in, request leave, download payslips." },
      { role: "Branch Manager", desc: "Approve leave, overtime and time fixes." },
      { role: "HR & Payroll", desc: "Run payroll, plan shifts, export reports." },
      { role: "Owner", desc: "Live attendance and labor cost, all branches." },
    ],
    statsTitle: "Core Capabilities",
    stats: [
      { value: "50–200m", label: "Branch geofence radius" },
      { value: "USD + KHR", label: "Dual-currency payroll" },
      { value: "< 1s", label: "Real-time cloud sync" },
    ],
    ctaTitle: "Try it with your own team.",
    ctaSub: "Set up your branches and run one real payroll before you decide.",
  },

  attendance: {
    title: "Clock-in you can trust.",
    sub: "GPS, selfie and time — recorded together, every shift.",
    heroImage: "Clock-in screen with branch radius",
    features: [
      { title: "GPS geofence", desc: "Set a 50–200 m radius per branch." },
      { title: "Selfie check", desc: "A photo is attached to every punch." },
      { title: "Mock-GPS defense", desc: "Spoofed locations are blocked." },
      { title: "Real-time cloud sync", desc: "Instant sync with central payroll." },
      { title: "QR kiosk", desc: "One shared tablet at the door." },
      { title: "Late reasons", desc: "Rain, traffic, breakdown, clinic." },
    ],
    splitTitle: "Know who is in, right now.",
    splitDesc: "A live roster per branch: present, late, on leave. Managers fix problems the same morning, not at month end.",
    splitImage: "Live attendance dashboard",
    ctaTitle: "See it on your own branches.",
  },

  payroll: {
    title: "Payroll without spreadsheets.",
    sub: "Configurable rules, USD and KHR, in one workflow.",
    heroImage: "Payslip in USD and KHR",
    formulaLabel: "Hourly rate",
    formula: "(Base salary ÷ working days) ÷ 8 hours",
    features: [
      { title: "Overtime multipliers", desc: "1.5× regular, 2.0× rest day and public holiday." },
      { title: "Grace periods", desc: "Set the minutes before a late deduction starts." },
      { title: "Dual currency", desc: "Every payslip in USD and KHR." },
      { title: "NSSF lines", desc: "Contributions itemised per employee." },
      { title: "Leave balances", desc: "Annual, sick, maternity and unpaid." },
      { title: "PDF payslips", desc: "Khmer or English, downloaded in the app." },
    ],
    simTitle: "Try the calculation.",
    simSub: "The same formula the payroll engine runs each month.",
    sim: {
      baseSalary: "Base salary",
      workingDays: "Working days",
      lateMinutes: "Late minutes",
      grace: "grace",
      otHours: "Overtime hours",
      otType: "Overtime type",
      hourly: "Hourly rate",
      late: "late",
      net: "Net take-home",
      min: "min",
      hrs: "h",
    },
    ctaTitle: "Close your next payroll in an afternoon.",
  },

  branches: {
    title: "One console, every branch.",
    sub: "Four levels of access, from owner to employee.",
    heroImage: "Multi-branch console",
    tiers: [
      { role: "Super Admin", desc: "Platform-level setup and support." },
      { role: "Owner / HR Admin", desc: "All branches, payroll and policy." },
      { role: "Branch Manager", desc: "Their own branches and approvals." },
      { role: "Employee", desc: "Self-service on mobile." },
    ],
    featuresTitle: "Made for real schedules.",
    features: [
      { title: "Overnight shifts", desc: "Shifts that cross midnight." },
      { title: "Split shifts", desc: "Morning and evening on one day." },
      { title: "Per-branch rules", desc: "Radius and grace period by location." },
      { title: "Store view", desc: "Owners can see any manager's console." },
    ],
    splitImage: "Shift planner",
    ctaTitle: "Add your branches in an afternoon.",
  },

  pricing: {
    title: "Simple pricing.",
    sub: "Per active user, per month. No setup fee.",
    monthly: "Monthly",
    annual: "Annual",
    annualBadge: "2 months free",
    perUser: "/user/mo",
    billedAnnually: "billed annually",
    popular: "Most popular",
    plans: [
      {
        id: "all-in-one",
        name: "All-in-One Plan",
        limit: "All features included • Unlimited branches",
        priceMonthly: 1.0,
        features: [
          "50–200m GPS geofencing & live selfie check",
          "Full Cambodian payroll engine ($ & ៛)",
          "Labor Law overtime (1.5×, 2.0×) & NSSF reports",
          "Shift planning, split shifts & leave management",
          "Unlimited branch outlets with zero extra fees",
          "QR door Kiosk mode & Real-time push notifications",
          "iOS & Android mobile apps + Admin web console",
          "Local Phnom Penh support via Telegram & phone",
        ],
      },
    ],
    note: "All features included in one transparent $1 plan. No setup fees, no per-branch surcharges, cancel anytime.",
    ctaTitle: "Ready to streamline your attendance & payroll?",
    ctaSub: "Get started in 15 minutes. Our Phnom Penh team is ready to assist your onboarding.",
  },

  customers: {
    title: "Workflows & team configurations.",
    sub: "Retail, F&B, logistics and hospitality profiles.",
    image: "Workforce operations in action",
    stats: [
      { value: "50–200m", label: "Configurable geofence radius" },
      { value: "USD + KHR", label: "Bilingual dual-currency payslips" },
      { value: "Real-Time Sync", label: "Instant live cloud updates" },
    ],

    ctaTitle: "Configure for your team.",
  },

  faq: {
    title: "Questions.",
    sub: "Short answers. Ask us anything else.",
    items: [
      {
        q: "How fast does attendance sync to central payroll?",
        a: "Attendance syncs instantly in real time. As soon as a frontline team member clocks in with GPS and selfie verification, the owner and HR dashboards update immediately.",
      },
      {
        q: "How do you stop fake GPS apps?",
        a: "Mock-location flags, impossible coordinate jumps and a required selfie inside the geofence. A failed check blocks the punch and logs the attempt.",
      },
      {
        q: "Can a manager cover several branches?",
        a: "Yes. Managers are assigned branches and see only those. Owners and HR admins see everything.",
      },
      {
        q: "Can I import employees from Excel?",
        a: "Yes. Fill in the template and upload it. Every row is validated before anything is saved.",
      },
      {
        q: "How does the dual-currency payslip work?",
        a: "Salary is stored in its contract currency. Payslips show USD and KHR side by side at your exchange rate.",
      },
      {
        q: "Does overtime follow Cambodian labor law?",
        a: "The standard multipliers ship by default — 1.5× regular, 2.0× rest day and public holiday — with the Cambodian holiday calendar. All rates are configurable.",
      },
      {
        q: "What about NSSF and seniority pay?",
        a: "Both appear as separate lines on the payslip, calculated per employee.",
      },
      {
        q: "How long is setup?",
        a: "Most companies are live in under a day. Growth and Enterprise get a guided session.",
      },
    ],
    ctaTitle: "Still have a question?",
  },

  about: {
    title: "Built in Phnom Penh.",
    sub: "For businesses that were told to make imported software fit.",
    image: "The AttendKH team",
    body: [
      "AttendKH started with one question from a coffee chain owner: who is actually at the branch right now?",
      "Global HR tools answered it in English, in USD, on a holiday calendar that was not ours. So we built the answer here — Khmer and English, riel and dollar, Cambodian labor rules in the formulas.",
      "Today teams in Phnom Penh, Siem Reap and Sihanoukville run their attendance and payroll on it, from single shops to fifty-branch groups.",
    ],
    valuesTitle: "How we work.",
    values: [
      { title: "Local first", desc: "Khmer is not a translation layer. It is the default." },
      { title: "Evidence", desc: "Every punch keeps its GPS, photo and audit trail." },
      { title: "Support here", desc: "Same time zone, same language, real people." },
    ],
    ctaTitle: "Come and see it.",
  },

  contact: {
    title: "Talk to us.",
    sub: "Demos, pricing and setup questions.",
    salesTitle: "Sales",
    salesDesc: "Book a demo or ask about a plan.",
    supportTitle: "Support",
    supportDesc: "For customers already running AttendKH.",
    officeTitle: "Office",
    hours: "Monday to Friday, 8:00 – 17:30 (ICT)",
    telegramCta: "Message us on Telegram",
    emailCta: "Send an email",
  },

  footer: {
    tagline: "Attendance and payroll for Cambodian teams.",
    productCol: "Product",
    solutionsCol: "Industries",
    companyCol: "Company",
    legalCol: "Legal",
    solutions: ["Retail", "Food & Beverage", "Logistics", "Tech & Agencies"],
    addressLabel: "Office",
    address: "Street 371, Phnom Penh, Cambodia",
    email: "support@MPG_by_ongphaly.com",
    telegram: "@MPG_by_ongphaly",
    apps: "Get the app",
    appStore: "App Store",
    play: "Google Play",
    rights: "© 2026 AttendKH Co., Ltd.",
    madeIn: "Made in Phnom Penh",
  },
};

export type SiteCopy = typeof en;

const km: SiteCopy = {
  nav: {
    attendance: "វត្តមាន",
    payroll: "ប្រាក់ខែ",
    branches: "ច្រើនសាខា",
    pricing: "តម្លៃ",
    customers: "អតិថិជន",
    faq: "សំណួរ",
    contact: "ទំនាក់ទំនង",
    signIn: "ចូលគណនី",
    trial: "ចាប់ផ្តើមប្រើប្រាស់",
    openMenu: "បើកម៉ឺនុយ",
    closeMenu: "បិទម៉ឺនុយ",
    language: "ភាសា",
    currency: "រូបិយប័ណ្ណ",
    skip: "រំលងទៅមាតិកា",
  },

  common: {
    trial: "ចាប់ផ្តើមប្រើប្រាស់",
    demo: "កក់ការបង្ហាញ",
    trialNote: "គ្មានថ្លៃដំឡើង។ បង់តែបុគ្គលិកសកម្ម។",
    learnMore: "ស្វែងយល់បន្ថែម",
    seeAll: "មើលមុខងារទាំងអស់",
    talkToSales: "ទាក់ទងផ្នែកលក់",
  },

  home: {
    badge: "សម្រាប់កម្ពុជា",
    title: "វត្តមាន និងប្រាក់ខែ នៅកន្លែងតែមួយ។",
    sub: "ចុះវត្តមានផ្ទៀងផ្ទាត់ដោយ GPS។ គណនាម៉ោងបន្ថែម និងការយឺតស្វ័យប្រវត្តិ។ ប័ណ្ណប្រាក់ខែជាដុល្លារ និងរៀល។",
    heroImage: "អេក្រង់ចុះវត្តមាន និងផ្ទាំងគ្រប់គ្រង",
    trust: "បង្កើតឡើងសម្រាប់អាជីវកម្មនៅកម្ពុជា • ភ្នំពេញ សៀមរាប ព្រះសីហនុ",
    pillarsTitle: "បញ្ហាបី ដោះស្រាយបាន។",
    pillars: [
      {
        title: "ចុះវត្តមានផ្ទៀងផ្ទាត់",
        desc: "បុគ្គលិកចុះវត្តមានក្នុងកាំសាខា ជាមួយរូបថតសម្រាប់អ្នកគ្រប់គ្រងពិនិត្យ។",
        href: "/attendance",
        image: "បុគ្គលិកកំពុងចុះវត្តមាននៅសាខា",
      },
      {
        title: "ប្រាក់ខែស្វ័យប្រវត្តិ",
        desc: "ម៉ោងបន្ថែម ការកាត់យឺត និងច្បាប់ឈប់ អនុវត្តដោយខ្លួនឯង។ ប័ណ្ណប្រាក់ខែមួយចុច។",
        href: "/payroll",
        image: "សេចក្តីសង្ខេបការបើកប្រាក់ខែ",
      },
      {
        title: "គ្រប់សាខា",
        desc: "កុងសូលតែមួយសម្រាប់គ្រប់ទីតាំង។ ប្រធានឃើញសាខាខ្លួន ម្ចាស់ឃើញទាំងអស់។",
        href: "/multi-branch",
        image: "ផែនទីទិដ្ឋភាពសាខា",
      },
    ],
    rolesTitle: "សម្រាប់ក្រុមទាំងមូល។",
    roles: [
      { role: "បុគ្គលិក", desc: "ចុះវត្តមាន សុំច្បាប់ ទាញយកប័ណ្ណប្រាក់ខែ។" },
      { role: "ប្រធានសាខា", desc: "អនុម័តច្បាប់ ម៉ោងបន្ថែម និងការកែម៉ោង។" },
      { role: "ធនធានមនុស្ស", desc: "បើកប្រាក់ខែ រៀបវេន នាំចេញរបាយការណ៍។" },
      { role: "ម្ចាស់អាជីវកម្ម", desc: "វត្តមានផ្ទាល់ និងចំណាយពលកម្មគ្រប់សាខា។" },
    ],
    statsTitle: "សមត្ថភាពស្នូល",
    stats: [
      { value: "៥០–២០០ម", label: "កាំ Geofence សាខា" },
      { value: "ដុល្លារ+រៀល", label: "ប័ណ្ណប្រាក់ខែពីររូបិយប័ណ្ណ" },
      { value: "< ១វិ", label: "សមកាលកម្ម Cloud ភ្លាមៗ" },
    ],
    ctaTitle: "សាកល្បងជាមួយក្រុមរបស់អ្នក។",
    ctaSub: "កំណត់សាខា ហើយបើកប្រាក់ខែពិតមួយដង មុនពេលសម្រេចចិត្ត។",
  },

  attendance: {
    title: "ការចុះវត្តមានដែលអាចទុកចិត្តបាន។",
    sub: "GPS រូបថត និងម៉ោង — កត់ត្រាជាមួយគ្នា រាល់វេន។",
    heroImage: "អេក្រង់ចុះវត្តមានជាមួយកាំសាខា",
    features: [
      { title: "GPS geofence", desc: "កំណត់កាំ ៥០–២០០ ម៉ែត្រ ក្នុងមួយសាខា។" },
      { title: "ផ្ទៀងផ្ទាត់រូបថត", desc: "រូបថតភ្ជាប់ជាមួយរាល់ការចុះវត្តមាន។" },
      { title: "ការពារ GPS ក្លែងក្លាយ", desc: "ទីតាំងក្លែងក្លាយត្រូវរារាំង។" },
      { title: "ធ្វើសមកាលកម្ម Cloud ផ្ទាល់", desc: "ធ្វើសមកាលកម្មភ្លាមៗជាមួយប្រព័ន្ធបើកប្រាក់ខែ។" },
      { title: "QR kiosk", desc: "ថេប្លេតរួមមួយនៅមាត់ទ្វារ។" },
      { title: "មូលហេតុយឺត", desc: "ភ្លៀង ស្ទះចរាចរណ៍ យានយន្តខូច ពេទ្យ។" },
    ],
    splitTitle: "ដឹងថានរណានៅ ពេលនេះ។",
    splitDesc: "តារាងផ្ទាល់តាមសាខា៖ មកធ្វើការ យឺត សុំច្បាប់។ ប្រធានដោះស្រាយបញ្ហាព្រឹកនោះ មិនមែនចុងខែ។",
    splitImage: "ផ្ទាំងវត្តមានផ្ទាល់",
    ctaTitle: "សាកមើលនៅសាខារបស់អ្នក។",
  },

  payroll: {
    title: "ប្រាក់ខែដោយមិនប្រើ Excel។",
    sub: "រូបមន្តកំណត់បាន ដុល្លារ និងរៀល នៅកន្លែងតែមួយ។",
    heroImage: "ប័ណ្ណប្រាក់ខែជាដុល្លារ និងរៀល",
    formulaLabel: "អត្រាម៉ោង",
    formula: "(ប្រាក់ខែមូលដ្ឋាន ÷ ថ្ងៃធ្វើការ) ÷ ៨ ម៉ោង",
    features: [
      { title: "មេគុណម៉ោងបន្ថែម", desc: "១.៥× ធម្មតា ២.០× ថ្ងៃសម្រាក និងបុណ្យជាតិ។" },
      { title: "រយៈពេលអនុគ្រោះ", desc: "កំណត់នាទីមុនពេលចាប់កាត់ប្រាក់។" },
      { title: "ពីររូបិយប័ណ្ណ", desc: "ប័ណ្ណប្រាក់ខែជាដុល្លារ និងរៀល។" },
      { title: "បន្ទាត់ បសស", desc: "វិភាគទានតាមបុគ្គលិកម្នាក់ៗ។" },
      { title: "សមតុល្យច្បាប់ឈប់", desc: "ប្រចាំឆ្នាំ ឈឺ សម្រាលកូន និងឥតប្រាក់ខែ។" },
      { title: "ប័ណ្ណប្រាក់ខែ PDF", desc: "ខ្មែរ ឬអង់គ្លេស ទាញយកក្នុងកម្មវិធី។" },
    ],
    simTitle: "សាកល្បងការគណនា។",
    simSub: "រូបមន្តដដែលដែលប្រព័ន្ធគណនារៀងរាល់ខែ។",
    sim: {
      baseSalary: "ប្រាក់ខែមូលដ្ឋាន",
      workingDays: "ថ្ងៃធ្វើការ",
      lateMinutes: "នាទីយឺត",
      grace: "អនុគ្រោះ",
      otHours: "ម៉ោងបន្ថែម",
      otType: "ប្រភេទម៉ោងបន្ថែម",
      hourly: "អត្រាម៉ោង",
      late: "យឺត",
      net: "ប្រាក់សុទ្ធទទួលបាន",
      min: "នាទី",
      hrs: "ម៉ោង",
    },
    ctaTitle: "បិទបញ្ជីប្រាក់ខែក្នុងមួយរសៀល។",
  },

  branches: {
    title: "កុងសូលតែមួយ គ្រប់សាខា។",
    sub: "សិទ្ធិបួនកម្រិត ពីម្ចាស់ដល់បុគ្គលិក។",
    heroImage: "កុងសូលច្រើនសាខា",
    tiers: [
      { role: "អ្នកគ្រប់គ្រងប្រព័ន្ធ", desc: "ការដំឡើង និងជំនួយកម្រិតវេទិកា។" },
      { role: "ម្ចាស់ / ធនធានមនុស្ស", desc: "គ្រប់សាខា ប្រាក់ខែ និងគោលនយោបាយ។" },
      { role: "ប្រធានសាខា", desc: "សាខារបស់ខ្លួន និងការអនុម័ត។" },
      { role: "បុគ្គលិក", desc: "សេវាខ្លួនឯងលើទូរស័ព្ទ។" },
    ],
    featuresTitle: "ធ្វើឡើងសម្រាប់វេនពិត។",
    features: [
      { title: "វេនយប់", desc: "វេនឆ្លងកាត់អធ្រាត្រ។" },
      { title: "វេនបំបែក", desc: "ព្រឹក និងល្ងាចក្នុងមួយថ្ងៃ។" },
      { title: "ច្បាប់តាមសាខា", desc: "កាំ និងរយៈពេលអនុគ្រោះតាមទីតាំង។" },
      { title: "ទិដ្ឋភាពសាខា", desc: "ម្ចាស់អាចមើលកុងសូលប្រធានណាមួយ។" },
    ],
    splitImage: "កម្មវិធីរៀបវេន",
    ctaTitle: "បញ្ចូលសាខារបស់អ្នកក្នុងមួយរសៀល។",
  },

  pricing: {
    title: "តម្លៃសាមញ្ញ។",
    sub: "តាមអ្នកប្រើសកម្មម្នាក់ក្នុងមួយខែ។ គ្មានថ្លៃដំឡើង។",
    monthly: "ប្រចាំខែ",
    annual: "ប្រចាំឆ្នាំ",
    annualBadge: "ឥតគិតថ្លៃ ២ ខែ",
    perUser: "/អ្នកប្រើ/ខែ",
    billedAnnually: "គិតថ្លៃប្រចាំឆ្នាំ",
    popular: "ពេញនិយមបំផុត",
    plans: [
      {
        id: "all-in-one",
        name: "គម្រោងរួមបញ្ចូលគ្រប់មុខងារ (All-in-One)",
        limit: "រួមបញ្ចូលគ្រប់មុខងារ • សាខាគ្មានដែនកំណត់",
        priceMonthly: 1.0,
        features: [
          "វត្តមាន GPS Geofence ៥០–២០០ម និង Selfie ការពារចុះជំនួស",
          "ប្រព័ន្ធបើកប្រាក់ខែកម្ពុជាពេញលេញ ($ និង ៛)",
          "ម៉ោងបន្ថែមច្បាប់ការងារ (១.៥x, ២.០x) និងរបាយការណ៍ ប.ស.ស.",
          "រៀបចំវេនការងារ វេនបំបែក និងការគ្រប់គ្រងច្បាប់ឈប់",
          "គ្រប់គ្រងច្រើនសាខា គ្មានការគិតប្រាក់បន្ថែមតាមសាខា",
          "មុខងារ QR Kiosk លើថេប្លេត និងការជូនដំណឹងតាមទូរស័ព្ទភ្លាមៗ",
          "កម្មវិធីទូរស័ព្ទ iOS/Android + ផ្ទាំងគ្រប់គ្រង Web Admin",
          "ជំនួយផ្ទាល់ពីភ្នំពេញតាម Telegram និងទូរស័ព្ទ",
        ],
      },
    ],
    note: "រួមបញ្ចូលគ្រប់មុខងារទាំងអស់ក្នុងតម្លៃតែមួយគត់ ១ ដុល្លារ/ខែ។ គ្មានថ្លៃដំឡើង គ្មានថ្លៃតាមសាខា។",
    ctaTitle: "ត្រៀមខ្លួនធ្វើឱ្យការគ្រប់គ្រងវត្តមាន និងប្រាក់ខែកាន់តែងាយស្រួល?",
    ctaSub: "ចាប់ផ្តើមក្នុងរយៈពេល ១៥ នាទី។ ក្រុមការងារនៅភ្នំពេញរបស់យើងត្រៀមជួយអ្នកជានិច្ច។",
  },

  customers: {
    title: "គំរូការងារ និងការកំណត់តាមក្រុម។",
    sub: "គំរូសម្រាប់វិស័យលក់រាយ ម្ហូបអាហារ ដឹកជញ្ជូន និងបដិសណ្ឋារកិច្ច។",
    image: "ក្រុមការងារប្រតិបត្តិការជាក់ស្តែង",
    stats: [
      { value: "៥០–២០០ម", label: "កាំ Geofence កំណត់តាមសាខា" },
      { value: "ដុល្លារ+រៀល", label: "ប័ណ្ណប្រាក់ខែទ្វេប្រាក់ទ្វេភាសា" },
      { value: "Real-Time Sync", label: "ធ្វើសមកាលកម្មទិន្នន័យផ្ទាល់" },
    ],

    ctaTitle: "រៀបចំសម្រាប់ក្រុមរបស់អ្នក។",
  },

  faq: {
    title: "សំណួរ។",
    sub: "ចម្លើយខ្លី។ សួរយើងបានគ្រប់ពេល។",
    items: [
      {
        q: "តើទិន្នន័យវត្តមានធ្វើសមកាលកម្មទៅប្រព័ន្ធប្រាក់ខែលឿនប៉ុនណា?",
        a: "វត្តមានធ្វើសមកាលកម្មភ្លាមៗតាម Real-Time។ នៅពេលបុគ្គលិកចុះវត្តមានជាមួយ GPS និងរូបថត ផ្ទាំងគ្រប់គ្រងរបស់ម្ចាស់ និង HR ទទួលបានព័ត៌មានភ្លាមៗ។",
      },
      {
        q: "តើអ្នកបញ្ឈប់កម្មវិធី GPS ក្លែងក្លាយយ៉ាងណា?",
        a: "សញ្ញា mock-location ការលោតកូអរដោនេមិនសមហេតុផល និងរូបថតចាំបាច់ក្នុង geofence។ បើបរាជ័យ ការចុះវត្តមានត្រូវរារាំង។",
      },
      {
        q: "តើប្រធានម្នាក់គ្រប់គ្រងច្រើនសាខាបានទេ?",
        a: "បាន។ ប្រធានឃើញតែសាខាដែលបានចាត់ឲ្យ។ ម្ចាស់ និងធនធានមនុស្សឃើញទាំងអស់។",
      },
      {
        q: "តើនាំចូលបុគ្គលិកពី Excel បានទេ?",
        a: "បាន។ បំពេញគំរូ រួចផ្ទុកឡើង។ រាល់ជួរត្រូវពិនិត្យមុនរក្សាទុក។",
      },
      {
        q: "ប័ណ្ណប្រាក់ខែពីររូបិយប័ណ្ណដំណើរការយ៉ាងណា?",
        a: "ប្រាក់ខែរក្សាទុកតាមរូបិយប័ណ្ណកិច្ចសន្យា។ ប័ណ្ណបង្ហាញដុល្លារ និងរៀលក្បែរគ្នា តាមអត្រារបស់អ្នក។",
      },
      {
        q: "តើអាចកំណត់រូបមន្តម៉ោងបន្ថែមបានទេ?",
        a: "បាន។ អ្នកអាចកំណត់មេគុណសម្រាប់ថ្ងៃធម្មតា ថ្ងៃសម្រាក និងថ្ងៃបុណ្យ។ សូមផ្ទៀងផ្ទាត់រូបមន្តជាមួយអ្នកជំនាញប្រាក់ខែ ឬច្បាប់មុនប្រើប្រាស់។",
      },
      {
        q: "ចុះ បសស និងប្រាក់អតីតភាពការងារ?",
        a: "ទាំងពីរបង្ហាញជាបន្ទាត់ដាច់ដោយឡែកលើប័ណ្ណប្រាក់ខែ គណនាតាមបុគ្គលិកម្នាក់ៗ។",
      },
      {
        q: "ការដំឡើងប្រើពេលប៉ុន្មាន?",
        a: "ក្រុមហ៊ុនភាគច្រើនចាប់ផ្តើមប្រើក្នុងតិចជាងមួយថ្ងៃ។ Growth និង Enterprise មានវគ្គណែនាំ។",
      },
    ],
    ctaTitle: "នៅមានសំណួរទៀត?",
  },

  about: {
    title: "បង្កើតនៅភ្នំពេញ។",
    sub: "សម្រាប់អាជីវកម្មដែលត្រូវបង្ខំឲ្យប្រើកម្មវិធីនាំចូល។",
    image: "ក្រុមការងារ AttendKH",
    body: [
      "AttendKH ចាប់ផ្តើមពីសំណួរមួយរបស់ម្ចាស់ហាងកាហ្វេ៖ តើអ្នកណានៅសាខាពេលនេះ?",
      "កម្មវិធីអន្តរជាតិជាច្រើនប្រើតែភាសាអង់គ្លេស និងដុល្លារ។ ដូច្នេះយើងបង្កើតចម្លើយនៅទីនេះ — ខ្មែរ និងអង់គ្លេស រៀល និងដុល្លារ និងរូបមន្តប្រាក់ខែដែលអាចកំណត់បាន។",
      "សព្វថ្ងៃ ក្រុមនៅភ្នំពេញ សៀមរាប និងព្រះសីហនុ ប្រើវាសម្រាប់វត្តមាន និងប្រាក់ខែ ចាប់ពីហាងតែមួយ ដល់ក្រុមហ៊ុន ៥០ សាខា។",
    ],
    valuesTitle: "របៀបយើងធ្វើការ។",
    values: [
      { title: "ក្នុងស្រុកមុនគេ", desc: "ភាសាខ្មែរមិនមែនជាស្រទាប់បកប្រែ។ វាជាភាសាដើម។" },
      { title: "ភស្តុតាង", desc: "រាល់ការចុះវត្តមានរក្សា GPS រូបថត និងកំណត់ហេតុ។" },
      { title: "ជំនួយនៅទីនេះ", desc: "ម៉ោងតែមួយ ភាសាតែមួយ មនុស្សពិត។" },
    ],
    ctaTitle: "អញ្ជើញមកមើល។",
  },

  contact: {
    title: "ទាក់ទងយើង។",
    sub: "ការបង្ហាញ តម្លៃ និងសំណួរដំឡើង។",
    salesTitle: "ផ្នែកលក់",
    salesDesc: "កក់ការបង្ហាញ ឬសួរអំពីគម្រោង។",
    supportTitle: "ជំនួយ",
    supportDesc: "សម្រាប់អតិថិជនដែលកំពុងប្រើ AttendKH។",
    officeTitle: "ការិយាល័យ",
    hours: "ច័ន្ទ ដល់ សុក្រ ៨:០០ – ១៧:៣០ (ICT)",
    telegramCta: "ផ្ញើសារតាម Telegram",
    emailCta: "ផ្ញើអ៊ីមែល",
  },

  footer: {
    tagline: "វត្តមាន និងប្រាក់ខែសម្រាប់ក្រុមការងារកម្ពុជា។",
    productCol: "ផលិតផល",
    solutionsCol: "វិស័យ",
    companyCol: "ក្រុមហ៊ុន",
    legalCol: "ផ្លូវច្បាប់",
    solutions: ["លក់រាយ", "ម្ហូបអាហារ", "ដឹកជញ្ជូន", "បច្ចេកវិទ្យា"],
    addressLabel: "ការិយាល័យ",
    address: "ផ្លូវ ៣៧១ រាជធានីភ្នំពេញ កម្ពុជា",
    email: "support@MPG_by_ongphaly.com",
    telegram: "@MPG_by_ongphaly",
    apps: "ទាញយកកម្មវិធី",
    appStore: "App Store",
    play: "Google Play",
    rights: "© ២០២៦ AttendKH Co., Ltd.",
    madeIn: "បង្កើតនៅភ្នំពេញ",
  },
};

const zh: SiteCopy = {
  nav: {
    attendance: "考勤打卡",
    payroll: "薪酬核算",
    branches: "多分店管理",
    pricing: "价格",
    customers: "合作客户",
    faq: "常见问题",
    contact: "联系我们",
    signIn: "登录后台",
    trial: "立即开通",
    openMenu: "打开菜单",
    closeMenu: "关闭菜单",
    language: "语言",
    currency: "币种",
    skip: "跳转至正文",
  },

  common: {
    trial: "立即开通使用",
    demo: "预约专家演示",
    trialNote: "无安装部署费，仅按实际员工数结算。",
    learnMore: "了解更多",
    seeAll: "查看全部功能",
    talkToSales: "咨询商务顾问",
  },

  home: {
    badge: "专为柬埔寨企业定制",
    title: "一站式搞定员工考勤与薪资核算。",
    sub: "GPS 围栏防作弊打卡，自动计算加班与迟到规则，一键导出美元与柬币标准工资单。",
    heroImage: "移动打卡界面与管理控制台",
    trust: "深受金边、暹粒、西港及全国各省本土企业信赖",
    pillarsTitle: "解决企业用工三大核心难题",
    pillars: [
      {
        title: "真实可信的打卡",
        desc: "员工必须在分店 GPS 范围内自拍打卡，杜绝代打卡与虚假定位。",
        href: "/attendance",
        image: "员工在分店门口自拍打卡",
      },
      {
        title: "智能化一键算薪",
        desc: "自动关联排班、平时/节假日加班倍率与迟到扣款，一键生成工资单。",
        href: "/payroll",
        image: "薪资结算汇总大盘",
      },
      {
        title: "全国多门店统一掌控",
        desc: "一个控制台管理所有分店。店长管理本店，老板统览全盘数据。",
        href: "/multi-branch",
        image: "多分店分布总览图",
      },
    ],
    rolesTitle: "为企业全员量身打造的协同体验",
    roles: [
      { role: "基层员工", desc: "手机秒速自拍打卡、发起请假调休、查收个人双语工资单。" },
      { role: "分店经理", desc: "审核本店请假、加班申请与补卡，实时掌握当班出勤率。" },
      { role: "HR 与薪酬主管", desc: "编排轮班表、一键核算全员薪资、导出 NSSF 报表与银行发薪表。" },
      { role: "企业创始人/老板", desc: "实时监控所有分店出勤动态与实时工时支出成本。" },
    ],
    statsTitle: "核心能力指标",
    stats: [
      { value: "50–200米", label: "分店 GPS 围栏半径" },
      { value: "USD + KHR", label: "美元与柬币双币结算" },
      { value: "< 1秒", label: "实时云端秒级同步" },
    ],
    ctaTitle: "即刻为您的团队开启体验。",
    ctaSub: "只需 5 分钟配置分店，即可完成首期全员薪资结算演练。",
  },

  attendance: {
    title: "每一次打卡，真实可信。",
    sub: "GPS 定位、真人照片与时间戳三重留痕，班次到岗情况一目了然。",
    heroImage: "带有分店半径的手机打卡界面",
    features: [
      { title: "GPS 地理围栏", desc: "地图上一键圈选 50–200 米有效打卡半径。" },
      { title: "真人活体自拍", desc: "每次打卡强制自拍并附带防伪水印。" },
      { title: "防作弊定位检测", desc: "自动识别并拦截虚拟定位软件与越狱插件。" },
      { title: "实时云端同步", desc: "考勤记录实时同步至中央薪资系统。" },
      { title: "前台公用平板模式", desc: "店门口设置公用考勤平板，扫码快速打卡。" },
      { title: "本土化迟到原因", desc: "大雨、堵车、车损、就医一键报备。" },
    ],
    splitTitle: "此时此刻，分店到岗情况一览无余。",
    splitDesc: "每家分店实时出勤大盘：在岗、迟到、请假实时刷新。店长在早班即可处理异常，无需拖延至月底。",
    splitImage: "实时考勤动态监控看板",
    ctaTitle: "在您的分店现场开启实测。",
  },

  payroll: {
    title: "彻底告别繁琐的 Excel 算薪。",
    sub: "灵活规则配置，美元（USD）与柬币（KHR）双币结算，一体化完成。",
    heroImage: "美元与柬币双币工资条",
    formulaLabel: "标准工时费率计算",
    formula: "( 基本月薪 ÷ 出勤天数 ) ÷ 8小时 = 标准时薪",
    features: [
      { title: "法定加班倍率", desc: "平时 1.5×，公休日与国家法定节假日 2.0×。" },
      { title: "灵活迟到宽限期", desc: "可设定 5–15 分钟免扣宽限，超时按分钟精准扣除。" },
      { title: "双币种核算", desc: "每位员工工资单均可同时展现美元与柬币。" },
      { title: "NSSF 社保明细", desc: "自动计算柬埔寨国家社保（ប.ស.ស.）扣缴明细。" },
      { title: "假期余额追踪", desc: "年假、病假、产假与事假自动关联扣除。" },
      { title: "高清 PDF 工资条", desc: "中、英、柬多语言工资条，员工可在 App 随时下载。" },
    ],
    simTitle: "交互式薪资试算器",
    simSub: "与每月系统自动化发薪引擎完全一致的底层计算公式。",
    sim: {
      baseSalary: "员工基本月薪",
      workingDays: "月工作天数",
      lateMinutes: "迟到总分钟数",
      grace: "宽限免扣",
      otHours: "加班总时长",
      otType: "加班薪资倍率",
      hourly: "计算所得标准时薪",
      late: "迟到扣款",
      net: "预计实发到手薪资",
      min: "分钟",
      hrs: "小时",
    },
    ctaTitle: "半天内轻松搞定全公司当月薪资。",
  },

  branches: {
    title: "一个控制台，统揽全国分店。",
    sub: "四级精细化权限隔离，从集团老板到基层员工各司其职。",
    heroImage: "多分店综合管理控制台",
    tiers: [
      { role: "超级管理员", desc: "掌管全平台底层配置、租户与系统安全。" },
      { role: "老板 / HR 总监", desc: "管理所有分店、全员薪资、组织架构与用工规则。" },
      { role: "分店经理", desc: "负责本店日常排班、考勤核准与请假审批。" },
      { role: "基层员工", desc: "移动端自拍打卡、发起审批并查收双语工资单。" },
    ],
    featuresTitle: "专为实际排班场景打造",
    features: [
      { title: "跨夜班次引擎", desc: "完美支持跨越午夜 12 点的连续夜班考勤。" },
      { title: "分段跨班次 (Split Shift)", desc: "支持同天安排早市、午市与晚高峰两段打卡。" },
      { title: "单店独立规则", desc: "可按分店位置设置独立的地理围栏半径与宽限期。" },
      { title: "老板穿透视角", desc: "企业高层可随时切换进入任意分店长的操作面板。" },
    ],
    splitImage: "智能轮班排程器",
    ctaTitle: "只需一个下午，完成所有分店接入。",
  },

  pricing: {
    title: "简单透明的价格体系。",
    sub: "按每月实际打卡人数计费，无任何安装部署附加费。",
    monthly: "按月付费",
    annual: "按年付费",
    annualBadge: "赠送 2 个月",
    perUser: "/人/月",
    billedAnnually: "按年结算更优惠",
    popular: "最受欢迎",
    plans: [
      {
        id: "all-in-one",
        name: "全功能一体化方案 (All-in-One)",
        limit: "解锁全部功能 • 无分店数量限制",
        priceMonthly: 1.0,
        features: [
          "50–200米 GPS 围栏打卡与防代打卡人脸自拍",
          "全功能柬埔寨双币种自动算薪引擎 ($ 与 ៛)",
          "法定加班倍率 (1.5×, 2.0×) 及 NSSF 社保一键导出",
          "智能轮班排程、分段班次与请假审批工作流",
          "无限多门店管理控制台（零分店附加费）",
          "平板门禁 QR Kiosk 模式与实时推送通知",
          "iOS / Android 移动端与 Web 企业管理后台",
          "金边本土中/英/柬三语专属技术支持",
        ],
      },
    ],
    note: "极简透明定价：每人每月仅需 1 美元，解锁全部核心功能，无任何安装部署与分店加价。",
    ctaTitle: "准备好升级您的企业考勤与薪酬管理了吗？",
    ctaSub: "15 分钟即可完成全员上线，金边技术团队随时为您提供全流程指引。",
  },

  customers: {
    title: "真实团队落地案例与业务场景。",
    sub: "涵盖连锁餐饮、精品零售、物流仓储及酒店服务业标杆客户。",
    image: "现场员工出勤操作实拍",
    stats: [
      { value: "50–200米", label: "可调地理围栏半径" },
      { value: "USD + KHR", label: "中英柬双语双币工资单" },
      { value: "实时云端同步", label: "毫秒级实时数据更新" },
    ],

    ctaTitle: "为您的团队定制配置方案。",
  },

  faq: {
    title: "常见疑问解答。",
    sub: "简明扼要的解答。如有其他问题，欢迎随时咨询。",
    items: [
      {
        q: "员工打卡后数据多久同步至总部后台？",
        a: "系统采用毫秒级实时云端同步。员工在现场完成 GPS 与真人自拍核验后，后台大盘与算薪引擎即刻实时刷新。",
      },
      {
        q: "如何防止员工使用虚拟定位（Fake GPS）作弊？",
        a: "系统内置多重反作弊防护机制：检测系统模拟定位标志、拦截不合常理的坐标突变，并强制要求在围栏范围内完成真人自拍核验。",
      },
      {
        q: "一位主管能否同时管理多家分店？",
        a: "可以。系统支持为每位主管分配特定分店管辖权，店长仅能查看所管辖门店，而集团创始人与 HR 总监拥有全店透视权限。",
      },
      {
        q: "能否从现有的 Excel 表格批量导入员工？",
        a: "可以。只需下载系统提供的标准模板并填入信息上传，系统会在导入前严格校验每一行数据格式，确保无差错。",
      },
      {
        q: "美元与柬币双币工资单是如何计算的？",
        a: "员工基本薪资按合同约定币种存储，工资单根据您在系统设定的汇率，同时并排呈现美元（USD）与柬币（KHR）换算明细。",
      },
      {
        q: "加班费计算是否符合柬埔寨劳工法？",
        a: "默认内置柬埔寨法定标准倍率：平时加班 1.5 倍，公休日与法定节假日 2.0 倍，并内置官方节假日日历。所有参数均可根据企业制度灵活调整。",
      },
      {
        q: "是否支持 NSSF 社保扣缴与工龄奖金计算？",
        a: "支持。工资单上会单独列明 NSSF（国家社保基金）员工与雇主分摊明细，以及工龄补偿金（Seniority Indemnity）条目。",
      },
      {
        q: "企业完成系统上线需要多久？",
        a: "大多数企业在半天之内即可完成配置并全员上线。成长版与企业版客户享有金边本土顾问一对一专属上线指导服务。",
      },
    ],
    ctaTitle: "还有其他疑问？",
  },

  about: {
    title: "诞生于金边，赋能本土企业。",
    sub: "专为不再迁就复杂海外软件的柬埔寨企业而造。",
    image: "AttendKH 金边核心团队",
    body: [
      "AttendKH 源于一位金边连锁咖啡店创始人的实际困扰：此时此刻，到底有谁真正到了哪家分店？",
      "市面上的海外 HR 软件全都是纯英文、只支持单一美元，且完全不符合柬埔寨当地的法定节假日与劳工法规定。因此，我们在金边亲自打造了这套系统——支持高棉语、中文与英语，支持美元与柬币双币核算，并将柬埔寨劳工法公式深植于底层代码中。",
      "今天，从金边、暹粒到西哈努克港，数百家企业正在 AttendKH 上高效管理员工考勤与薪资结算。",
    ],
    valuesTitle: "我们的核心原则",
    values: [
      { title: "本土优先", desc: "高棉语与本土习惯不是外挂翻译层，而是系统与生俱来的默认底座。" },
      { title: "真实留痕", desc: "每一次打卡均包含 GPS 定位、真人照片与防篡改审计日志。" },
      { title: "金边本土支持", desc: "相同的时区、相同的语言、由金边本土真实工程师提供即时保障。" },
    ],
    ctaTitle: "欢迎莅临交流。",
  },

  contact: {
    title: "与我们取得联系。",
    sub: "产品演示、方案报价及系统配置咨询。",
    salesTitle: "商务咨询",
    salesDesc: "预约产品演示或定制报价方案。",
    supportTitle: "客户服务",
    supportDesc: "为 AttendKH 在用企业提供即时技术保障。",
    officeTitle: "金边办公室",
    hours: "周一至周五，8:00 – 17:30 (ICT)",
    telegramCta: "在 Telegram 上联系我们",
    emailCta: "发送电子邮件",
  },

  footer: {
    tagline: "专为柬埔寨企业量身定制的智能考勤与薪资系统。",
    productCol: "产品服务",
    solutionsCol: "行业方案",
    companyCol: "关于企业",
    legalCol: "合规条款",
    solutions: ["连锁零售", "餐饮美食", "物流仓储", "科技与数字机构"],
    addressLabel: "办公室地址",
    address: "柬埔寨金边市 371 街",
    email: "support@MPG_by_ongphaly.com",
    telegram: "@MPG_by_ongphaly",
    apps: "下载移动端",
    appStore: "App Store",
    play: "Google Play",
    rights: "© 2026 AttendKH Co., Ltd.",
    madeIn: "金边制造",
  },
};

export const siteCopy: Record<Lang, SiteCopy> = { en, km, zh };
