import type { Lang } from "@/lib/i18n";

/** Marketing copy for every page, English and Khmer. Kept deliberately short. */
const en = {
  nav: {
    attendance: "Attendance",
    payroll: "Payroll",
    branches: "Multi-Branch",
    pricing: "Pricing",
    customers: "Customers",
    faq: "FAQ",
    contact: "Contact",
    signIn: "Sign In",
    trial: "Start Free Trial",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "Language",
    currency: "Currency",
    skip: "Skip to content",
  },

  common: {
    trial: "Start free trial",
    demo: "Book a demo",
    trialNote: "14 days free. No card required.",
    learnMore: "Learn more",
    seeAll: "See all features",
    talkToSales: "Talk to sales",
  },

  home: {
    badge: "Built for Cambodia",
    title: "Attendance and payroll, done in one place.",
    sub: "GPS-verified clock-in. Automatic overtime and late rules. Payslips in USD and KHR.",
    heroImage: "App clock-in screen and admin dashboard",
    trust: "Built for Cambodian businesses • Phnom Penh, Siem Reap, Sihanoukville",
    pillarsTitle: "Three problems, solved.",
    pillars: [
      {
        title: "Verified clock-in",
        desc: "Staff clock in inside the branch radius, with a selfie. No buddy punching.",
        href: "/attendance",
        image: "Employee clocking in at a branch",
      },
      {
        title: "Automatic payroll",
        desc: "Apply configured overtime, late, and leave rules, then export payslips.",
        href: "/payroll",
        image: "Payroll run summary",
      },
      {
        title: "Every branch",
        desc: "One console for all locations. Managers see their site, owners see everything.",
        href: "/multi-branch",
        image: "Branch overview map",
      },
    ],
    rolesTitle: "Built for the whole team.",
    roles: [
      { role: "Employee", desc: "Clock in, request leave, download payslips." },
      { role: "Branch Manager", desc: "Approve leave, overtime and time fixes." },
      { role: "HR & Payroll", desc: "Run payroll, plan shifts, export reports." },
      { role: "Owner", desc: "Live attendance and labor cost, all branches." },
    ],
    statsTitle: "Core Capabilities",
    stats: [
      { value: "50–200m", label: "Branch geofence radius" },
      { value: "USD + KHR", label: "Dual-currency payroll" },
      { value: "Queued", label: "Offline sync support" },
    ],
    ctaTitle: "Try it with your own team.",
    ctaSub: "Set up your branches and run one real payroll before you decide.",
  },

  attendance: {
    title: "Clock-in you can trust.",
    sub: "GPS, selfie and time — recorded together, every shift.",
    heroImage: "Clock-in screen with branch radius",
    features: [
      { title: "GPS geofence", desc: "Set a 50–200 m radius per branch." },
      { title: "Selfie check", desc: "A photo is attached to every punch." },
      { title: "Mock-GPS defense", desc: "Spoofed locations are blocked." },
      { title: "Works offline", desc: "Syncs when the network returns." },
      { title: "QR kiosk", desc: "One shared tablet at the door." },
      { title: "Late reasons", desc: "Rain, traffic, breakdown, clinic." },
    ],
    splitTitle: "Know who is in, right now.",
    splitDesc: "A live roster per branch: present, late, on leave. Managers fix problems the same morning, not at month end.",
    splitImage: "Live attendance dashboard",
    ctaTitle: "See it on your own branches.",
  },

  payroll: {
    title: "Payroll without spreadsheets.",
    sub: "Configurable rules, USD and KHR, in one workflow.",
    heroImage: "Payslip in USD and KHR",
    formulaLabel: "Hourly rate",
    formula: "(Base salary ÷ working days) ÷ 8 hours",
    features: [
      { title: "Overtime multipliers", desc: "1.5× regular, 2.0× rest day and public holiday." },
      { title: "Grace periods", desc: "Set the minutes before a late deduction starts." },
      { title: "Dual currency", desc: "Every payslip in USD and KHR." },
      { title: "NSSF lines", desc: "Contributions itemised per employee." },
      { title: "Leave balances", desc: "Annual, sick, maternity and unpaid." },
      { title: "PDF payslips", desc: "Khmer or English, downloaded in the app." },
    ],
    simTitle: "Try the calculation.",
    simSub: "The same formula the payroll engine runs each month.",
    sim: {
      baseSalary: "Base salary",
      workingDays: "Working days",
      lateMinutes: "Late minutes",
      grace: "grace",
      otHours: "Overtime hours",
      otType: "Overtime type",
      hourly: "Hourly rate",
      late: "late",
      net: "Net take-home",
      min: "min",
      hrs: "h",
    },
    ctaTitle: "Close your next payroll in an afternoon.",
  },

  branches: {
    title: "One console, every branch.",
    sub: "Four levels of access, from owner to employee.",
    heroImage: "Multi-branch console",
    tiers: [
      { role: "Super Admin", desc: "Platform-level setup and support." },
      { role: "Owner / HR Admin", desc: "All branches, payroll and policy." },
      { role: "Branch Manager", desc: "Their own branches and approvals." },
      { role: "Employee", desc: "Self-service on mobile." },
    ],
    featuresTitle: "Made for real schedules.",
    features: [
      { title: "Overnight shifts", desc: "Shifts that cross midnight." },
      { title: "Split shifts", desc: "Morning and evening on one day." },
      { title: "Per-branch rules", desc: "Radius and grace period by location." },
      { title: "Store view", desc: "Owners can see any manager's console." },
    ],
    splitImage: "Shift planner",
    ctaTitle: "Add your branches in an afternoon.",
  },

  pricing: {
    title: "Simple pricing.",
    sub: "Per active user, per month. No setup fee.",
    monthly: "Monthly",
    annual: "Annual",
    annualBadge: "2 months free",
    perUser: "/user/mo",
    billedAnnually: "billed annually",
    popular: "Most popular",
    plans: [
      {
        id: "starter",
        name: "Starter",
        limit: "Up to 20 users",
        priceMonthly: 1.5,
        features: ["GPS attendance", "Leave tracking", "Mobile app", "Basic reports"],
      },
      {
        id: "growth",
        name: "Growth",
        limit: "Up to 150 users",
        priceMonthly: 2.5,
        features: [
          "Everything in Starter",
          "Full payroll engine",
          "Selfie verification",
          "Overtime multipliers",
          "Shift planner",
          "Expense claims",
        ],
      },
      {
        id: "enterprise",
        name: "Enterprise",
        limit: "Unlimited users",
        priceMonthly: 3.5,
        features: [
          "Everything in Growth",
          "Custom roles",
          "API access",
          "Custom labor rules",
          "Account manager",
        ],
      },
    ],
    note: "All plans include the mobile app, web console and local support in Khmer and English.",
    ctaTitle: "Not sure which plan?",
    ctaSub: "Tell us your headcount and branches. We will point you to the right one.",
  },

  customers: {
    title: "Workflows & team configurations.",
    sub: "Retail, F&B, logistics and hospitality profiles.",
    image: "Workforce operations in action",
    stats: [
      { value: "50–200m", label: "Configurable geofence radius" },
      { value: "USD + KHR", label: "Bilingual dual-currency payslips" },
      { value: "Offline Sync", label: "Local device punch queueing" },
    ],
    testimonials: [
      {
        quote: "Split shifts between lunch and dinner services are tracked with a 50m branch geofence and live selfie verification.",
        name: "F&B Operations",
        role: "Multi-Shift Profile",
        company: "Restaurant & Cafe Workflows",
      },
      {
        quote: "Area managers track floor punctuality across multiple shopping malls with automated late arrival deduction rules.",
        name: "Retail Boutiques",
        role: "Multi-Store Profile",
        company: "Shopping Mall & Street Outlets",
      },
      {
        quote: "Department rosters coordinate rotational shifts with configurable night and public-holiday payroll multipliers.",
        name: "Hospitality & Resorts",
        role: "24/7 Roster Profile",
        company: "Hotel & Resort Operations",
      },
    ],
    ctaTitle: "Configure for your team.",
  },

  faq: {
    title: "Questions.",
    sub: "Short answers. Ask us anything else.",
    items: [
      {
        q: "What if there is no internet at the branch?",
        a: "The app clocks in offline and syncs when the network returns. The recorded time is the clock-in time, not the sync time.",
      },
      {
        q: "How do you stop fake GPS apps?",
        a: "Mock-location flags, impossible coordinate jumps and a required selfie inside the geofence. A failed check blocks the punch and logs the attempt.",
      },
      {
        q: "Can a manager cover several branches?",
        a: "Yes. Managers are assigned branches and see only those. Owners and HR admins see everything.",
      },
      {
        q: "Can I import employees from Excel?",
        a: "Yes. Fill in the template and upload it. Every row is validated before anything is saved.",
      },
      {
        q: "How does the dual-currency payslip work?",
        a: "Salary is stored in its contract currency. Payslips show USD and KHR side by side at your exchange rate.",
      },
      {
        q: "Does overtime follow Cambodian labor law?",
        a: "The standard multipliers ship by default — 1.5× regular, 2.0× rest day and public holiday — with the Cambodian holiday calendar. All rates are configurable.",
      },
      {
        q: "What about NSSF and seniority pay?",
        a: "Both appear as separate lines on the payslip, calculated per employee.",
      },
      {
        q: "How long is setup?",
        a: "Most companies are live in under a day. Growth and Enterprise get a guided session.",
      },
    ],
    ctaTitle: "Still have a question?",
  },

  about: {
    title: "Built in Phnom Penh.",
    sub: "For businesses that were told to make imported software fit.",
    image: "The AttendKH team",
    body: [
      "AttendKH started with one question from a coffee chain owner: who is actually at the branch right now?",
      "Global HR tools answered it in English, in USD, on a holiday calendar that was not ours. So we built the answer here — Khmer and English, riel and dollar, Cambodian labor rules in the formulas.",
      "Today teams in Phnom Penh, Siem Reap and Sihanoukville run their attendance and payroll on it, from single shops to fifty-branch groups.",
    ],
    valuesTitle: "How we work.",
    values: [
      { title: "Local first", desc: "Khmer is not a translation layer. It is the default." },
      { title: "Evidence", desc: "Every punch keeps its GPS, photo and audit trail." },
      { title: "Support here", desc: "Same time zone, same language, real people." },
    ],
    ctaTitle: "Come and see it.",
  },

  contact: {
    title: "Talk to us.",
    sub: "Demos, pricing and setup questions.",
    salesTitle: "Sales",
    salesDesc: "Book a demo or ask about a plan.",
    supportTitle: "Support",
    supportDesc: "For customers already running AttendKH.",
    officeTitle: "Office",
    hours: "Monday to Friday, 8:00 – 17:30 (ICT)",
    telegramCta: "Message us on Telegram",
    emailCta: "Send an email",
  },

  footer: {
    tagline: "Attendance and payroll for Cambodian teams.",
    productCol: "Product",
    solutionsCol: "Industries",
    companyCol: "Company",
    legalCol: "Legal",
    solutions: ["Retail", "Food & Beverage", "Logistics", "Tech & Agencies"],
    addressLabel: "Office",
    address: "No. 12, Street 315, Toul Kork, Phnom Penh, Cambodia",
    email: "support@attendkh.com",
    telegram: "@attendkh",
    apps: "Get the app",
    appStore: "App Store",
    play: "Google Play",
    rights: "© 2026 AttendKH Co., Ltd.",
    madeIn: "Made in Phnom Penh",
  },
};

export type SiteCopy = typeof en;

const km: SiteCopy = {
  nav: {
    attendance: "វត្តមាន",
    payroll: "ប្រាក់ខែ",
    branches: "ច្រើនសាខា",
    pricing: "តម្លៃ",
    customers: "អតិថិជន",
    faq: "សំណួរ",
    contact: "ទំនាក់ទំនង",
    signIn: "ចូលគណនី",
    trial: "សាកល្បងឥតគិតថ្លៃ",
    openMenu: "បើកម៉ឺនុយ",
    closeMenu: "បិទម៉ឺនុយ",
    language: "ភាសា",
    currency: "រូបិយប័ណ្ណ",
    skip: "រំលងទៅមាតិកា",
  },

  common: {
    trial: "សាកល្បងឥតគិតថ្លៃ",
    demo: "កក់ការបង្ហាញ",
    trialNote: "ឥតគិតថ្លៃ ១៤ ថ្ងៃ។ មិនត្រូវការកាត។",
    learnMore: "ស្វែងយល់បន្ថែម",
    seeAll: "មើលមុខងារទាំងអស់",
    talkToSales: "ទាក់ទងផ្នែកលក់",
  },

  home: {
    badge: "សម្រាប់កម្ពុជា",
    title: "វត្តមាន និងប្រាក់ខែ នៅកន្លែងតែមួយ។",
    sub: "ចុះវត្តមានផ្ទៀងផ្ទាត់ដោយ GPS។ គណនាម៉ោងបន្ថែម និងការយឺតស្វ័យប្រវត្តិ។ ប័ណ្ណប្រាក់ខែជាដុល្លារ និងរៀល។",
    heroImage: "អេក្រង់ចុះវត្តមាន និងផ្ទាំងគ្រប់គ្រង",
    trust: "បង្កើតឡើងសម្រាប់អាជីវកម្មនៅកម្ពុជា • ភ្នំពេញ សៀមរាប ព្រះសីហនុ",
    pillarsTitle: "បញ្ហាបី ដោះស្រាយបាន។",
    pillars: [
      {
        title: "ចុះវត្តមានផ្ទៀងផ្ទាត់",
        desc: "បុគ្គលិកចុះវត្តមានក្នុងកាំសាខា ជាមួយរូបថតសម្រាប់អ្នកគ្រប់គ្រងពិនិត្យ។",
        href: "/attendance",
        image: "បុគ្គលិកកំពុងចុះវត្តមាននៅសាខា",
      },
      {
        title: "ប្រាក់ខែស្វ័យប្រវត្តិ",
        desc: "ម៉ោងបន្ថែម ការកាត់យឺត និងច្បាប់ឈប់ អនុវត្តដោយខ្លួនឯង។ ប័ណ្ណប្រាក់ខែមួយចុច។",
        href: "/payroll",
        image: "សេចក្តីសង្ខេបការបើកប្រាក់ខែ",
      },
      {
        title: "គ្រប់សាខា",
        desc: "កុងសូលតែមួយសម្រាប់គ្រប់ទីតាំង។ ប្រធានឃើញសាខាខ្លួន ម្ចាស់ឃើញទាំងអស់។",
        href: "/multi-branch",
        image: "ផែនទីទិដ្ឋភាពសាខា",
      },
    ],
    rolesTitle: "សម្រាប់ក្រុមទាំងមូល។",
    roles: [
      { role: "បុគ្គលិក", desc: "ចុះវត្តមាន សុំច្បាប់ ទាញយកប័ណ្ណប្រាក់ខែ។" },
      { role: "ប្រធានសាខា", desc: "អនុម័តច្បាប់ ម៉ោងបន្ថែម និងការកែម៉ោង។" },
      { role: "ធនធានមនុស្ស", desc: "បើកប្រាក់ខែ រៀបវេន នាំចេញរបាយការណ៍។" },
      { role: "ម្ចាស់អាជីវកម្ម", desc: "វត្តមានផ្ទាល់ និងចំណាយពលកម្មគ្រប់សាខា។" },
    ],
    statsTitle: "សមត្ថភាពស្នូល",
    stats: [
      { value: "៥០–២០០ម", label: "កាំ Geofence សាខា" },
      { value: "ដុល្លារ+រៀល", label: "ប័ណ្ណប្រាក់ខែពីររូបិយប័ណ្ណ" },
      { value: "Queued", label: "គាំទ្រការធ្វើសមកាលកម្មក្រៅបណ្តាញ" },
    ],
    ctaTitle: "សាកល្បងជាមួយក្រុមរបស់អ្នក។",
    ctaSub: "កំណត់សាខា ហើយបើកប្រាក់ខែពិតមួយដង មុនពេលសម្រេចចិត្ត។",
  },

  attendance: {
    title: "ការចុះវត្តមានដែលអាចទុកចិត្តបាន។",
    sub: "GPS រូបថត និងម៉ោង — កត់ត្រាជាមួយគ្នា រាល់វេន។",
    heroImage: "អេក្រង់ចុះវត្តមានជាមួយកាំសាខា",
    features: [
      { title: "GPS geofence", desc: "កំណត់កាំ ៥០–២០០ ម៉ែត្រ ក្នុងមួយសាខា។" },
      { title: "ផ្ទៀងផ្ទាត់រូបថត", desc: "រូបថតភ្ជាប់ជាមួយរាល់ការចុះវត្តមាន។" },
      { title: "ការពារ GPS ក្លែងក្លាយ", desc: "ទីតាំងក្លែងក្លាយត្រូវរារាំង។" },
      { title: "ដំណើរការក្រៅបណ្តាញ", desc: "ធ្វើសមកាលកម្មពេលបណ្តាញត្រឡប់មក។" },
      { title: "QR kiosk", desc: "ថេប្លេតរួមមួយនៅមាត់ទ្វារ។" },
      { title: "មូលហេតុយឺត", desc: "ភ្លៀង ស្ទះចរាចរណ៍ យានយន្តខូច ពេទ្យ។" },
    ],
    splitTitle: "ដឹងថានរណានៅ ពេលនេះ។",
    splitDesc: "តារាងផ្ទាល់តាមសាខា៖ មកធ្វើការ យឺត សុំច្បាប់។ ប្រធានដោះស្រាយបញ្ហាព្រឹកនោះ មិនមែនចុងខែ។",
    splitImage: "ផ្ទាំងវត្តមានផ្ទាល់",
    ctaTitle: "សាកមើលនៅសាខារបស់អ្នក។",
  },

  payroll: {
    title: "ប្រាក់ខែដោយមិនប្រើ Excel។",
    sub: "រូបមន្តកំណត់បាន ដុល្លារ និងរៀល នៅកន្លែងតែមួយ។",
    heroImage: "ប័ណ្ណប្រាក់ខែជាដុល្លារ និងរៀល",
    formulaLabel: "អត្រាម៉ោង",
    formula: "(ប្រាក់ខែមូលដ្ឋាន ÷ ថ្ងៃធ្វើការ) ÷ ៨ ម៉ោង",
    features: [
      { title: "មេគុណម៉ោងបន្ថែម", desc: "១.៥× ធម្មតា ២.០× ថ្ងៃសម្រាក និងបុណ្យជាតិ។" },
      { title: "រយៈពេលអនុគ្រោះ", desc: "កំណត់នាទីមុនពេលចាប់កាត់ប្រាក់។" },
      { title: "ពីររូបិយប័ណ្ណ", desc: "ប័ណ្ណប្រាក់ខែជាដុល្លារ និងរៀល។" },
      { title: "បន្ទាត់ បសស", desc: "វិភាគទានតាមបុគ្គលិកម្នាក់ៗ។" },
      { title: "សមតុល្យច្បាប់ឈប់", desc: "ប្រចាំឆ្នាំ ឈឺ សម្រាលកូន និងឥតប្រាក់ខែ។" },
      { title: "ប័ណ្ណប្រាក់ខែ PDF", desc: "ខ្មែរ ឬអង់គ្លេស ទាញយកក្នុងកម្មវិធី។" },
    ],
    simTitle: "សាកល្បងការគណនា។",
    simSub: "រូបមន្តដដែលដែលប្រព័ន្ធគណនារៀងរាល់ខែ។",
    sim: {
      baseSalary: "ប្រាក់ខែមូលដ្ឋាន",
      workingDays: "ថ្ងៃធ្វើការ",
      lateMinutes: "នាទីយឺត",
      grace: "អនុគ្រោះ",
      otHours: "ម៉ោងបន្ថែម",
      otType: "ប្រភេទម៉ោងបន្ថែម",
      hourly: "អត្រាម៉ោង",
      late: "យឺត",
      net: "ប្រាក់សុទ្ធទទួលបាន",
      min: "នាទី",
      hrs: "ម៉ោង",
    },
    ctaTitle: "បិទបញ្ជីប្រាក់ខែក្នុងមួយរសៀល។",
  },

  branches: {
    title: "កុងសូលតែមួយ គ្រប់សាខា។",
    sub: "សិទ្ធិបួនកម្រិត ពីម្ចាស់ដល់បុគ្គលិក។",
    heroImage: "កុងសូលច្រើនសាខា",
    tiers: [
      { role: "អ្នកគ្រប់គ្រងប្រព័ន្ធ", desc: "ការដំឡើង និងជំនួយកម្រិតវេទិកា។" },
      { role: "ម្ចាស់ / ធនធានមនុស្ស", desc: "គ្រប់សាខា ប្រាក់ខែ និងគោលនយោបាយ។" },
      { role: "ប្រធានសាខា", desc: "សាខារបស់ខ្លួន និងការអនុម័ត។" },
      { role: "បុគ្គលិក", desc: "សេវាខ្លួនឯងលើទូរស័ព្ទ។" },
    ],
    featuresTitle: "ធ្វើឡើងសម្រាប់វេនពិត។",
    features: [
      { title: "វេនយប់", desc: "វេនឆ្លងកាត់អធ្រាត្រ។" },
      { title: "វេនបំបែក", desc: "ព្រឹក និងល្ងាចក្នុងមួយថ្ងៃ។" },
      { title: "ច្បាប់តាមសាខា", desc: "កាំ និងរយៈពេលអនុគ្រោះតាមទីតាំង។" },
      { title: "ទិដ្ឋភាពសាខា", desc: "ម្ចាស់អាចមើលកុងសូលប្រធានណាមួយ។" },
    ],
    splitImage: "កម្មវិធីរៀបវេន",
    ctaTitle: "បញ្ចូលសាខារបស់អ្នកក្នុងមួយរសៀល។",
  },

  pricing: {
    title: "តម្លៃសាមញ្ញ។",
    sub: "តាមអ្នកប្រើសកម្មម្នាក់ក្នុងមួយខែ។ គ្មានថ្លៃដំឡើង។",
    monthly: "ប្រចាំខែ",
    annual: "ប្រចាំឆ្នាំ",
    annualBadge: "ឥតគិតថ្លៃ ២ ខែ",
    perUser: "/អ្នកប្រើ/ខែ",
    billedAnnually: "គិតថ្លៃប្រចាំឆ្នាំ",
    popular: "ពេញនិយមបំផុត",
    plans: [
      {
        id: "starter",
        name: "Starter",
        limit: "រហូតដល់ ២០ អ្នកប្រើ",
        priceMonthly: 1.5,
        features: ["វត្តមាន GPS", "តាមដានច្បាប់ឈប់", "កម្មវិធីទូរស័ព្ទ", "របាយការណ៍មូលដ្ឋាន"],
      },
      {
        id: "growth",
        name: "Growth",
        limit: "រហូតដល់ ១៥០ អ្នកប្រើ",
        priceMonthly: 2.5,
        features: [
          "គ្រប់យ៉ាងក្នុង Starter",
          "ប្រព័ន្ធបើកប្រាក់ខែពេញលេញ",
          "ផ្ទៀងផ្ទាត់រូបថត",
          "មេគុណម៉ោងបន្ថែម",
          "កម្មវិធីរៀបវេន",
          "ការទាមទារចំណាយ",
        ],
      },
      {
        id: "enterprise",
        name: "Enterprise",
        limit: "អ្នកប្រើគ្មានដែនកំណត់",
        priceMonthly: 3.5,
        features: [
          "គ្រប់យ៉ាងក្នុង Growth",
          "តួនាទីតាមតម្រូវការ",
          "ការចូលប្រើ API",
          "ច្បាប់ការងារផ្ទាល់ខ្លួន",
          "អ្នកគ្រប់គ្រងគណនី",
        ],
      },
    ],
    note: "គ្រប់គម្រោងរួមបញ្ចូលកម្មវិធីទូរស័ព្ទ កុងសូលគេហទំព័រ និងជំនួយក្នុងស្រុកជាភាសាខ្មែរ និងអង់គ្លេស។",
    ctaTitle: "មិនច្បាស់ថាគម្រោងណា?",
    ctaSub: "ប្រាប់យើងពីចំនួនបុគ្គលិក និងសាខា។ យើងនឹងណែនាំគម្រោងត្រឹមត្រូវ។",
  },

  customers: {
    title: "គំរូការងារ និងការកំណត់តាមក្រុម។",
    sub: "គំរូសម្រាប់វិស័យលក់រាយ ម្ហូបអាហារ ដឹកជញ្ជូន និងបដិសណ្ឋារកិច្ច។",
    image: "ក្រុមការងារប្រតិបត្តិការជាក់ស្តែង",
    stats: [
      { value: "៥០–២០០ម", label: "កាំ Geofence កំណត់តាមសាខា" },
      { value: "ដុល្លារ+រៀល", label: "ប័ណ្ណប្រាក់ខែទ្វេប្រាក់ទ្វេភាសា" },
      { value: "Offline Sync", label: "រក្សាទុកទិន្នន័យក្នុងទូរស័ព្ទ" },
    ],
    testimonials: [
      {
        quote: "វេនបំបែករវាងពេលថ្ងៃត្រង់ និងពេលល្ងាច ត្រូវបានតាមដានតាមកាំសាខា ៥០ម និងរូបថត selfie ជាក់ស្តែង។",
        name: "ផ្នែកម្ហូបអាហារ និងភេសជ្ជៈ",
        role: "គំរូវេនបំបែក",
        company: "ភោជនីយដ្ឋាន និងហាងកាហ្វេ",
      },
      {
        quote: "អ្នកគ្រប់គ្រងសាខាតាមផ្សារទំនើបតាមដានវត្តមានទាន់ពេល និងច្បាប់កាត់ប្រាក់យឺតស្វ័យប្រវត្តិ។",
        name: "ហាងលក់រាយ និងម៉ាត",
        role: "គំរូច្រើនសាខា",
        company: "សាខាតាមផ្សារទំនើប និងដងផ្លូវ",
      },
      {
        quote: "កាលវិភាគតាមផ្នែកគ្រប់គ្រងវេនបង្វិល ២៤/៧ ជាមួយមេគុណម៉ោងបន្ថែមពេលយប់ និងថ្ងៃបុណ្យជាតិ។",
        name: "សណ្ឋាគារ និងរីសត",
        role: "គំរូវេន ២៤/៧",
        company: "សណ្ឋាគារ និងបដិសណ្ឋារកិច្ច",
      },
    ],
    ctaTitle: "រៀបចំសម្រាប់ក្រុមរបស់អ្នក។",
  },

  faq: {
    title: "សំណួរ។",
    sub: "ចម្លើយខ្លី។ សួរយើងបានគ្រប់ពេល។",
    items: [
      {
        q: "បើគ្មានអ៊ីនធឺណិតនៅសាខាតើយ៉ាងណា?",
        a: "កម្មវិធីចុះវត្តមានក្រៅបណ្តាញ ហើយធ្វើសមកាលកម្មពេលបណ្តាញត្រឡប់មក។ ម៉ោងកត់ត្រាគឺម៉ោងចុះវត្តមានពិត។",
      },
      {
        q: "តើអ្នកបញ្ឈប់កម្មវិធី GPS ក្លែងក្លាយយ៉ាងណា?",
        a: "សញ្ញា mock-location ការលោតកូអរដោនេមិនសមហេតុផល និងរូបថតចាំបាច់ក្នុង geofence។ បើបរាជ័យ ការចុះវត្តមានត្រូវរារាំង។",
      },
      {
        q: "តើប្រធានម្នាក់គ្រប់គ្រងច្រើនសាខាបានទេ?",
        a: "បាន។ ប្រធានឃើញតែសាខាដែលបានចាត់ឲ្យ។ ម្ចាស់ និងធនធានមនុស្សឃើញទាំងអស់។",
      },
      {
        q: "តើនាំចូលបុគ្គលិកពី Excel បានទេ?",
        a: "បាន។ បំពេញគំរូ រួចផ្ទុកឡើង។ រាល់ជួរត្រូវពិនិត្យមុនរក្សាទុក។",
      },
      {
        q: "ប័ណ្ណប្រាក់ខែពីររូបិយប័ណ្ណដំណើរការយ៉ាងណា?",
        a: "ប្រាក់ខែរក្សាទុកតាមរូបិយប័ណ្ណកិច្ចសន្យា។ ប័ណ្ណបង្ហាញដុល្លារ និងរៀលក្បែរគ្នា តាមអត្រារបស់អ្នក។",
      },
      {
        q: "តើអាចកំណត់រូបមន្តម៉ោងបន្ថែមបានទេ?",
        a: "បាន។ អ្នកអាចកំណត់មេគុណសម្រាប់ថ្ងៃធម្មតា ថ្ងៃសម្រាក និងថ្ងៃបុណ្យ។ សូមផ្ទៀងផ្ទាត់រូបមន្តជាមួយអ្នកជំនាញប្រាក់ខែ ឬច្បាប់មុនប្រើប្រាស់។",
      },
      {
        q: "ចុះ បសស និងប្រាក់អតីតភាពការងារ?",
        a: "ទាំងពីរបង្ហាញជាបន្ទាត់ដាច់ដោយឡែកលើប័ណ្ណប្រាក់ខែ គណនាតាមបុគ្គលិកម្នាក់ៗ។",
      },
      {
        q: "ការដំឡើងប្រើពេលប៉ុន្មាន?",
        a: "ក្រុមហ៊ុនភាគច្រើនចាប់ផ្តើមប្រើក្នុងតិចជាងមួយថ្ងៃ។ Growth និង Enterprise មានវគ្គណែនាំ។",
      },
    ],
    ctaTitle: "នៅមានសំណួរទៀត?",
  },

  about: {
    title: "បង្កើតនៅភ្នំពេញ។",
    sub: "សម្រាប់អាជីវកម្មដែលត្រូវបង្ខំឲ្យប្រើកម្មវិធីនាំចូល។",
    image: "ក្រុមការងារ AttendKH",
    body: [
      "AttendKH ចាប់ផ្តើមពីសំណួរមួយរបស់ម្ចាស់ហាងកាហ្វេ៖ តើអ្នកណានៅសាខាពេលនេះ?",
      "កម្មវិធីអន្តរជាតិជាច្រើនប្រើតែភាសាអង់គ្លេស និងដុល្លារ។ ដូច្នេះយើងបង្កើតចម្លើយនៅទីនេះ — ខ្មែរ និងអង់គ្លេស រៀល និងដុល្លារ និងរូបមន្តប្រាក់ខែដែលអាចកំណត់បាន។",
      "សព្វថ្ងៃ ក្រុមនៅភ្នំពេញ សៀមរាប និងព្រះសីហនុ ប្រើវាសម្រាប់វត្តមាន និងប្រាក់ខែ ចាប់ពីហាងតែមួយ ដល់ក្រុមហ៊ុន ៥០ សាខា។",
    ],
    valuesTitle: "របៀបយើងធ្វើការ។",
    values: [
      { title: "ក្នុងស្រុកមុនគេ", desc: "ភាសាខ្មែរមិនមែនជាស្រទាប់បកប្រែ។ វាជាភាសាដើម។" },
      { title: "ភស្តុតាង", desc: "រាល់ការចុះវត្តមានរក្សា GPS រូបថត និងកំណត់ហេតុ។" },
      { title: "ជំនួយនៅទីនេះ", desc: "ម៉ោងតែមួយ ភាសាតែមួយ មនុស្សពិត។" },
    ],
    ctaTitle: "អញ្ជើញមកមើល។",
  },

  contact: {
    title: "ទាក់ទងយើង។",
    sub: "ការបង្ហាញ តម្លៃ និងសំណួរដំឡើង។",
    salesTitle: "ផ្នែកលក់",
    salesDesc: "កក់ការបង្ហាញ ឬសួរអំពីគម្រោង។",
    supportTitle: "ជំនួយ",
    supportDesc: "សម្រាប់អតិថិជនដែលកំពុងប្រើ AttendKH។",
    officeTitle: "ការិយាល័យ",
    hours: "ច័ន្ទ ដល់ សុក្រ ៨:០០ – ១៧:៣០ (ICT)",
    telegramCta: "ផ្ញើសារតាម Telegram",
    emailCta: "ផ្ញើអ៊ីមែល",
  },

  footer: {
    tagline: "វត្តមាន និងប្រាក់ខែសម្រាប់ក្រុមការងារកម្ពុជា។",
    productCol: "ផលិតផល",
    solutionsCol: "វិស័យ",
    companyCol: "ក្រុមហ៊ុន",
    legalCol: "ផ្លូវច្បាប់",
    solutions: ["លក់រាយ", "ម្ហូបអាហារ", "ដឹកជញ្ជូន", "បច្ចេកវិទ្យា"],
    addressLabel: "ការិយាល័យ",
    address: "លេខ ១២ ផ្លូវ ៣១៥ ខណ្ឌទួលគោក រាជធានីភ្នំពេញ",
    email: "support@attendkh.com",
    telegram: "@attendkh",
    apps: "ទាញយកកម្មវិធី",
    appStore: "App Store",
    play: "Google Play",
    rights: "© ២០២៦ AttendKH Co., Ltd.",
    madeIn: "បង្កើតនៅភ្នំពេញ",
  },
};

export const siteCopy: Record<Lang, SiteCopy> = { en, km };
